name: Terraform CI/CD with AI Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: plan
        type: choice
        options:
          - apply
          - plan

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.11.4'

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init 2>&1 | tee ../terraform.log
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request' || github.event.inputs.action == 'plan'
        run: |
          cd terraform
          terraform plan -out=tfplan 2>&1 | tee -a ../terraform.log
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: |
          cd terraform
          terraform apply -auto-approve 2>&1 | tee -a ../terraform.log
        continue-on-error: true

      - name: Analyze Terraform Errors with AI
        if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' || steps.apply.outcome == 'failure'
        uses: your-username/terraform-ai-analyzer@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terraform-directory: './terraform'
          auto-fix: 'true'
          branch-name: 'ai-terraform-fixes'


      - name: Fail workflow if Terraform failed
        if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' || steps.apply.outcome == 'failure'
        run: |
          echo "Terraform failed. Check the AI analysis results above."
          exit 1